config/routes.rb
Rails.application.routes.draw do
  
  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :name
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
     @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id]) #showページを開いた地点のデータを取得
    gon.place = @place
    @places = Place.where.not(id: @place.id)  #@placeのid以外のデータを取得
    gon.places = @places
    @lat = @place.latitude
    @lng = @place.longitude
    gon.lat = @lat
    gon.lng = @lng
    gon.lats = []
    gon.lngs = []
    @places.each do |places|
      gon.lats << places.latitude
      gon.lngs << places.longitude
    end
    @hash = Gmaps4rails.build_markers(@place) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow place.name
    end
    
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :description, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gmap
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    -# %script{:src => "//maps.google.com/maps/api/js?key=AIzaSyAU8Lqc8zivL85a3FicZriuI5a_J8II3fA"}
    %script{:src => "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}

    = yield

app/views/places/_form.html.haml
= form_with(model: place, local: true) do |form|
  - if place.errors.any?
    #error_explanation
      %h2
        = pluralize(place.errors.count, "error")
        prohibited this place from being saved:
      %ul
        - place.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :description
    = form.text_field :description
  .actions
    = form.submit

app/views/places/edit.html.haml
%h1 Editing Place
= render 'form', place: @place
= link_to 'Show', @place
|
= link_to 'Back', places_path

%div{:style => "width: 100%;"}
  #map{:style => "width: 100%; height: 600px;"}

app/views/places/index.html.haml
%p#notice= notice
%h1 Places
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Latitude
      %th Longitude
      %th{:colspan => "3"}
  %tbody
    - @places.each do |place|
      %tr
        %td= place.name
        %td= place.description
        %td= place.latitude
        %td= place.longitude
        %td= link_to 'Show', place
        %td= link_to 'Edit', edit_place_path(place)
        %td= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Place', new_place_path

-# %div{:style => "width: 100%;"}
-#   #map{:style => "width: 100%; height: 600px;"}

-# :javascript
-#   handler = Gmaps.build('Google');
-#   handler.buildMap({ 
-#     provider: {},
-#     internal: {id: 'map'}
-#     }, 
-#     function(){
-#     markers = handler.addMarkers(#{raw @hash.to_json})
-#     handler.bounds.extendWith(markers);
-#     handler.fitMapToBounds();
-#     handler.getMap().setCenter(new google.maps.LatLng(35.681298, 139.7640582));
-#     handler.getMap().setZoom(15);
-#   });

app/views/places/new.html.haml
%h1 New Place
= render 'form', place: @place
= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @place.name
%p
  %strong Description:
  = @place.description
%p
  %strong Latitude:
  = @place.latitude
%p
  %strong Longitude:
  = @place.longitude
= link_to 'Edit', edit_place_path(@place)
|
= link_to 'Back', places_path, data: {"turbolinks" => false}





%head
  :css
    #gmap1, #gmap2, #gmap3 {
      height: 400px;
      width: 800px;
    }
    
%body
  %p.gmapTitle1 １番目に近い地点
  %p.gmapTitle1 １番目に近い地点
  .gamp1#gmap1
  %p.gmapTitle2 2番目に近い地点
  .gmap2#gmap2
  %p.gmapTitle3 3番目に近い地点
  .gmap3#gmap3
  / 地図を表示する領域
  :javascript
    function initMap() { 
      // 地図を生成して表示
      var map1 = new google.maps.Map(document.getElementById("gmap1"), {
        zoom: 13,
        center: new google.maps.LatLng(gon.lat, gon.lng),  //Madison Av/E 38 St
        mapTypeId: "roadmap"
        
      });
      var map2 = new google.maps.Map(document.getElementById("gmap2"), {
        zoom: 13,
        center: new google.maps.LatLng(gon.lat, gon.lng),  //Madison Av/E 38 St
        mapTypeId: "roadmap"
        
      });
      var map3 = new google.maps.Map(document.getElementById("gmap3"), {
        zoom: 13,
        center: new google.maps.LatLng(gon.lat, gon.lng),  //Madison Av/E 38 St
        mapTypeId: "roadmap"
        
      });
      
      //DirectionsService のオブジェクトを生成
      var directionsService1 = new google.maps.DirectionsService();
      var directionsService2 = new google.maps.DirectionsService();
      var directionsService3 = new google.maps.DirectionsService();
      //DirectionsRenderer のオブジェクトを生成
      var directionsRenderer1 = new google.maps.DirectionsRenderer();
      var directionsRenderer2 = new google.maps.DirectionsRenderer();
      var directionsRenderer3 = new google.maps.DirectionsRenderer();
      //directionsRenderer と地図を紐付け
      directionsRenderer1.setMap(map1); 
      directionsRenderer2.setMap(map2); 
      directionsRenderer3.setMap(map3);
      //リクエストの出発点の位置（Empire State Building 出発地点の緯度経度）
      var start = new google.maps.LatLng(gon.lat, gon.lng);  
      //リクエストの終着点の位置（Grand Central Station 到着地点の緯度経度）
      
      
      var ends = new Array;
      ends = [];
      var distanceOrigin = new Array;
      distanceOrigin = [];
      var distanceClone = new Array;
      distanceClone = [];
      var distanceEdit = new Array;
      distanceEdit = [];
      for (var i = 0; i < gon.lats.length; i++) {
        ends.push(new google.maps.LatLng(gon.lats[i], gon.lngs[i]));
      }
      for (var j = 0; j < gon.lats.length; j++) {
        distanceOrigin[j] = google.maps.geometry.spherical.computeDistanceBetween(start, ends[j]);
        distanceClone[j] = google.maps.geometry.spherical.computeDistanceBetween(start, ends[j]);
        if (distanceOrigin[j] === Math.min.apply(null, distanceOrigin)) {
          var end1 = ends[j];
          var goalName1 = gon.places[j].name
          startName = gon.place.name
        }
      } 
      function compare(a, b){
        let comparison = 0;

        if (a > b) {
          comparison = 1;
        } else if (b > a) {
          comparison = -1;
        }

        return comparison;
      }

      distanceEdit = distanceClone.sort(compare);

      for (var i = 0; i < gon.lats.length; i++) {
        if (distanceOrigin[i] === distanceEdit[1]) {
          var end2 = ends[i];
          var goalName2 = gon.places[i].name;
        }
        if (distanceOrigin[i] === distanceEdit[2]) {
          var end3 = ends[i];
          var goalName3 = gon.places[i].name;
        }
        
      }
      var Start_infowindow1 = new google.maps.InfoWindow({
        content: startName,
        position: start
      });
      var Start_infowindow2 = new google.maps.InfoWindow({
        content: startName,
        position: start
      });
      var Start_infowindow3 = new google.maps.InfoWindow({
        content: startName,
        position: start
      });
      var End_infowindow1 = new google.maps.InfoWindow({
        content: goalName1,
        position: end1
      });
      var End_infowindow2 = new google.maps.InfoWindow({
        content: goalName2,
        position: end2
      });
      var End_infowindow3 = new google.maps.InfoWindow({
        content: goalName3,
        position: end3
      });
      
       // ルートを取得するリクエスト
      var request1 = {
        origin: start,      // 出発地点の緯度経度
        destination: end1,   // 到着地点の緯度経度
        travelMode: 'WALKING' //トラベルモード（歩き）
      };
       var request2 = {
        origin: start,      // 出発地点の緯度経度
        destination: end2,   // 到着地点の緯度経度
        travelMode: 'WALKING' //トラベルモード（歩き）
      };
       var request3 = {
        origin: start,      // 出発地点の緯度経度
        destination: end3,   // 到着地点の緯度経度
        travelMode: 'WALKING' //トラベルモード（歩き）
      };

      //DirectionsService のオブジェクトのメソッド route() にリクエストを渡し、
      //コールバック関数で結果を setDirections(result) で directionsRenderer にセットして表示
      directionsService1.route(request1, function(result, status) {
        //ステータスがOKの場合、
        if (status === 'OK') {
          directionsRenderer1.setDirections(result); //取得したルート（結果：result）をセット
          Start_infowindow1.open(map1);
          End_infowindow1.open(map1);
        }else{
          alert("取得できませんでした：" + status);
        }
      });
      directionsService2.route(request2, function(result, status) {
        //ステータスがOKの場合、
        if (status === 'OK') {
          directionsRenderer2.setDirections(result); //取得したルート（結果：result）をセット
          Start_infowindow2.open(map2);
          End_infowindow2.open(map2);
        }else{
          alert("取得できませんでした：" + status);
        }
      });
      directionsService3.route(request3, function(result, status) {
        //ステータスがOKの場合、
        if (status === 'OK') {
          directionsRenderer3.setDirections(result); //取得したルート（結果：result）をセット
          Start_infowindow3.open(map3);
          End_infowindow3.open(map3);
        }else{
          alert("取得できませんでした：" + status);
        }
      });
      
    };


    
   
  %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAU8Lqc8zivL85a3FicZriuI5a_J8II3fA&callback=initMap&libraries=geometry"}
  
  / YOUR_API_KEYの部分は取得した APIキーで置き換えます。